spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc?characterEncoding=utf8
    username: root
    password: 935377012
  session:
    store-type: none
imooc:
  security:
    code:
      iamge:
        length: 5